spring.application.name=JavaSpringBoot4
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
job_Title=Software Engineer,\
  Data Analyst,\
  Product Manager,\
  Marketing Specialist,\
  Data Scientist,\
  Business Analyst,\
  Cloud Architect,\
  UI/UX Designer,\
  System Administrator,\
  UX Designer,\
  DevOps Engineer,\
  Front-End Developer,\
  Back-End Developer,\
  QA Tester,\
  Product Owner


